// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PersonProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Test.opensource.protobuf.model {

  /// <summary>Holder for reflection information generated from PersonProto.proto</summary>
  public static partial class PersonProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for PersonProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PersonProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQZXJzb25Qcm90by5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90",
            "byL0AQoLUGVyc29uUHJvdG8SCgoCaWQYASABKAUSDAoEbmFtZRgCIAEoCRIL",
            "CgNhZ2UYAyABKAUSFwoGZ2VuZGVyGAUgASgOMgcuR2VuZGVyEgwKBHNvbnMY",
            "BCADKAkSKgoHc29uSm9icxgGIAMoCzIZLlBlcnNvblByb3RvLlNvbkpvYnNF",
            "bnRyeRISCgRqb2JzGAcgAygLMgQuSm9iEiEKA2FueRgIIAMoCzIULmdvb2ds",
            "ZS5wcm90b2J1Zi5BbnkaNAoMU29uSm9ic0VudHJ5EgsKA2tleRgBIAEoCRIT",
            "CgV2YWx1ZRgCIAEoCzIELkpvYjoCOAEiIwoDSm9iEgwKBG5hbWUYASABKAkS",
            "DgoGc2FsYXJ5GAIgASgBKhwKBkdlbmRlchIHCgNNQU4QABIJCgVXT01BThAB",
            "QiGqAh5UZXN0Lm9wZW5zb3VyY2UucHJvdG9idWYubW9kZWxiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Test.opensource.protobuf.model.Gender), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Test.opensource.protobuf.model.PersonProto), global::Test.opensource.protobuf.model.PersonProto.Parser, new[]{ "Id", "Name", "Age", "Gender", "Sons", "SonJobs", "Jobs", "Any" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Test.opensource.protobuf.model.Job), global::Test.opensource.protobuf.model.Job.Parser, new[]{ "Name", "Salary" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///成员嵌套类型
  /// </summary>
  public enum Gender {
    [pbr::OriginalName("MAN")] Man = 0,
    [pbr::OriginalName("WOMAN")] Woman = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  ///待会还要把生成的Person 拷贝到工程
  ///option java_outer_classname = "PersonProto";//生成的类名--C#里没有此选项
  /// </summary>
  public sealed partial class PersonProto : pb::IMessage<PersonProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PersonProto> _parser = new pb::MessageParser<PersonProto>(() => new PersonProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PersonProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Test.opensource.protobuf.model.PersonProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonProto(PersonProto other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      age_ = other.age_;
      gender_ = other.gender_;
      sons_ = other.sons_.Clone();
      sonJobs_ = other.sonJobs_.Clone();
      jobs_ = other.jobs_.Clone();
      any_ = other.any_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonProto Clone() {
      return new PersonProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 3;
    private int age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 5;
    private global::Test.opensource.protobuf.model.Gender gender_ = global::Test.opensource.protobuf.model.Gender.Man;
    /// <summary>
    /// Enum值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Test.opensource.protobuf.model.Gender Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "sons" field.</summary>
    public const int SonsFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_sons_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> sons_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Sons {
      get { return sons_; }
    }

    /// <summary>Field number for the "sonJobs" field.</summary>
    public const int SonJobsFieldNumber = 6;
    private static readonly pbc::MapField<string, global::Test.opensource.protobuf.model.Job>.Codec _map_sonJobs_codec
        = new pbc::MapField<string, global::Test.opensource.protobuf.model.Job>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Test.opensource.protobuf.model.Job.Parser), 50);
    private readonly pbc::MapField<string, global::Test.opensource.protobuf.model.Job> sonJobs_ = new pbc::MapField<string, global::Test.opensource.protobuf.model.Job>();
    /// <summary>
    /// 定义Map对象
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::Test.opensource.protobuf.model.Job> SonJobs {
      get { return sonJobs_; }
    }

    /// <summary>Field number for the "jobs" field.</summary>
    public const int JobsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Test.opensource.protobuf.model.Job> _repeated_jobs_codec
        = pb::FieldCodec.ForMessage(58, global::Test.opensource.protobuf.model.Job.Parser);
    private readonly pbc::RepeatedField<global::Test.opensource.protobuf.model.Job> jobs_ = new pbc::RepeatedField<global::Test.opensource.protobuf.model.Job>();
    /// <summary>
    /// List列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Test.opensource.protobuf.model.Job> Jobs {
      get { return jobs_; }
    }

    /// <summary>Field number for the "any" field.</summary>
    public const int AnyFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Any> _repeated_any_codec
        = pb::FieldCodec.ForMessage(66, global::Google.Protobuf.WellKnownTypes.Any.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> any_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any>();
    /// <summary>
    /// Any对象,泛型。可以用作分页数据的data:List&lt;T>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Any> Any {
      get { return any_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PersonProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PersonProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Age != other.Age) return false;
      if (Gender != other.Gender) return false;
      if(!sons_.Equals(other.sons_)) return false;
      if (!SonJobs.Equals(other.SonJobs)) return false;
      if(!jobs_.Equals(other.jobs_)) return false;
      if(!any_.Equals(other.any_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      if (Gender != global::Test.opensource.protobuf.model.Gender.Man) hash ^= Gender.GetHashCode();
      hash ^= sons_.GetHashCode();
      hash ^= SonJobs.GetHashCode();
      hash ^= jobs_.GetHashCode();
      hash ^= any_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      sons_.WriteTo(output, _repeated_sons_codec);
      if (Gender != global::Test.opensource.protobuf.model.Gender.Man) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Gender);
      }
      sonJobs_.WriteTo(output, _map_sonJobs_codec);
      jobs_.WriteTo(output, _repeated_jobs_codec);
      any_.WriteTo(output, _repeated_any_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      sons_.WriteTo(ref output, _repeated_sons_codec);
      if (Gender != global::Test.opensource.protobuf.model.Gender.Man) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Gender);
      }
      sonJobs_.WriteTo(ref output, _map_sonJobs_codec);
      jobs_.WriteTo(ref output, _repeated_jobs_codec);
      any_.WriteTo(ref output, _repeated_any_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      if (Gender != global::Test.opensource.protobuf.model.Gender.Man) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gender);
      }
      size += sons_.CalculateSize(_repeated_sons_codec);
      size += sonJobs_.CalculateSize(_map_sonJobs_codec);
      size += jobs_.CalculateSize(_repeated_jobs_codec);
      size += any_.CalculateSize(_repeated_any_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PersonProto other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      if (other.Gender != global::Test.opensource.protobuf.model.Gender.Man) {
        Gender = other.Gender;
      }
      sons_.Add(other.sons_);
      sonJobs_.Add(other.sonJobs_);
      jobs_.Add(other.jobs_);
      any_.Add(other.any_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 34: {
            sons_.AddEntriesFrom(input, _repeated_sons_codec);
            break;
          }
          case 40: {
            Gender = (global::Test.opensource.protobuf.model.Gender) input.ReadEnum();
            break;
          }
          case 50: {
            sonJobs_.AddEntriesFrom(input, _map_sonJobs_codec);
            break;
          }
          case 58: {
            jobs_.AddEntriesFrom(input, _repeated_jobs_codec);
            break;
          }
          case 66: {
            any_.AddEntriesFrom(input, _repeated_any_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 34: {
            sons_.AddEntriesFrom(ref input, _repeated_sons_codec);
            break;
          }
          case 40: {
            Gender = (global::Test.opensource.protobuf.model.Gender) input.ReadEnum();
            break;
          }
          case 50: {
            sonJobs_.AddEntriesFrom(ref input, _map_sonJobs_codec);
            break;
          }
          case 58: {
            jobs_.AddEntriesFrom(ref input, _repeated_jobs_codec);
            break;
          }
          case 66: {
            any_.AddEntriesFrom(ref input, _repeated_any_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///成员嵌套类型
  /// </summary>
  public sealed partial class Job : pb::IMessage<Job>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Job> _parser = new pb::MessageParser<Job>(() => new Job());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Job> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Test.opensource.protobuf.model.PersonProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Job() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Job(Job other) : this() {
      name_ = other.name_;
      salary_ = other.salary_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Job Clone() {
      return new Job(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "salary" field.</summary>
    public const int SalaryFieldNumber = 2;
    private double salary_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Salary {
      get { return salary_; }
      set {
        salary_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Job);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Job other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Salary, other.Salary)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Salary != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Salary);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Salary != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Salary);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Salary != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Salary);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Salary != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Job other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Salary != 0D) {
        Salary = other.Salary;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 17: {
            Salary = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 17: {
            Salary = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
